[package]
name = "fleetspeak-proto"
version = "0.1.0"
license = "MIT"
authors = ["≈Åukasz Hanuszczak <hanuszczak@google.com>"]
edition = "2018"

exclude = [
  "!/proto/**/*.proto",
]

[dependencies]
prost = { version = "0.6.1" }
prost-types = { version = "0.6.1" }

[build-dependencies]
prost-build = { version = "0.6.1" }
