[package]
name = "fleetspeak-proto"
version = "0.1.0"
description = "A Fleetspeak connector crate with Protocol Buffers messages."
license = "MIT"
authors = ["≈Åukasz Hanuszczak <hanuszczak@google.com>"]
homepage = "https://github.com/google/fleetspeak-rs"
documentation = "https://docs.rs/fleetspeak-proto"
repository = "https://github.com/google/fleetspeak-rs"
edition = "2018"

exclude = [
  "!/proto/**/*.proto",
]

[dependencies]
prost = { version = "0.6.1" }
prost-types = { version = "0.6.1" }

[build-dependencies]
prost-build = { version = "0.6.1" }
